# Generated by Django 3.2.7 on 2021-09-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
